### ISSUE TITLE
Conversion from Scala BitSet with no copy

### ISSUE THREAD

**Issue by ms-tg** [denisrosset/metal#20]
The immutable `BitSet.toScala` method currently invokes the `fromBitMaskNoCopy` method to avoid copying the backing array. Would it be possible to implement a similar functionality on the metal BitSet to convert in the other direction (ie from Scala) without copying?

**Comment by ms-tg** [comment]
Nevermind -- it appears that the `metal.immutable.BitSet.fromIterable` actually is special cased to do what I am requesting here if the argument is a scala BitSet. Is that correct?

**Comment by denisrosset** [comment]
Yes, but the Scala side is a bit messy, some stuff is protected, some stuff is public, it should really be made more consistent.

For example, the first word in `BitSet2` is publicly available (`val`), but not the second one.

**Comment by ms-tg** [comment]
Got it. My case is always `BitSetN`, so in this case, the `fromIterable` constructor will take the existing `Array[Long]` without copying, right?

I see what you mean on `BitSet2`, doesn't apply to me at this time though ;)

(also -- thanks for a _great_ mini library here. Just dropping in let us solve performance problems of Sets in an inner loop with no further effort)
